### ISSUE TITLE
AWS credentials should be stored in a k8s secret

### ISSUE THREAD

**Issue by StefanTheWiz** [hellofresh/kangal#119]
At the moment the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are stored in a config map. 
Shouldn't these be stored in a secret?

**Comment by diegomarangoni** [comment]
hey @StefanTheWiz, thanks for reporting.
yes, it would be better to store it in a secret.

I just added this to our backlog
