### ISSUE TITLE
Not installing the latest version

### ISSUE THREAD

**Issue by QAInsights** [hellofresh/kangal#121]
Upon following the instructions in README, helm is not installing the latest version (1.1.11). It is installing 1.4.9. Could you please release the `helm release`?

```
apiVersion: v1
description: Run JMeter performance tests in Kubernetes cluster with Kangal
home: https://github.com/hellofresh/kangal
icon: https://raw.githubusercontent.com/hellofresh/kangal/master/logo.svg
keywords:
- kubernetes
- jmeter
- performance tests
- tests runner
maintainers:
- email: kangal@hellofresh.com
  name: Kangal
name: kangal
version: 1.4.9

```

**Comment by diegomarangoni** [comment]
hey @QAInsights, the helm chart and Kangal itself have a different version number.
If you see on releases pages, all the ones with `kangal-` prefix are related to the helm chart only.

**Comment by QAInsights** [comment]
thanks @diegomarangoni but kangal-1.4.9 doesn't have the fix which you did for the report. Correct me if I am wrong :)

**Comment by diegomarangoni** [comment]
the chart default `values.yaml` file points to latest image kangal version, [see here](https://github.com/hellofresh/kangal/blob/master/charts/kangal/values.yaml#L13)

you might be using a cached docker image, so you can manually overwrite lines 14 & 87 on your `values.yaml` file and point to the version you want

**Comment by diegomarangoni** [comment]
here is an example:

```yaml
proxy:
  # Number of pods to run
  replicaCount: 2

  image:
    repository: hellofresh/kangal
    tag: 1.1.11
    pullPolicy: Always
```

**Comment by QAInsights** [comment]
Yes, I changed the values to 1.1.11. It is displaying the following error.

**Comment by diegomarangoni** [comment]
can you share the command you run and the `values.yaml` file?

**Comment by QAInsights** [comment]
Command is ``` helm install kangal . ````

**Comment by QAInsights** [comment]
YAML file https://gist.github.com/QAInsights/0966facf23b021c33d0ad20094930a84

**Comment by diegomarangoni** [comment]
thanks for sharing.
please take a look at chart documentation at [charts/kangal/](https://github.com/hellofresh/kangal/tree/master/charts/kangal).

you are missing the `--set environment=dev` part:

```bash
helm install \
  --set environment=dev \
  kangal .
```

**Comment by diegomarangoni** [comment]
closing it, feel free to reopen in case still not working
