### ISSUE TITLE
Allow secure access to S3

### ISSUE THREAD

**Issue by jleft** [hellofresh/kangal#126]
Firstly, thank you for this project!

The MinIO client, configured for report uploading, is initialised with `secure` set to `false` (in the [`NewWithCredentials`](https://pkg.go.dev/gopkg.in/minio/minio-go.v6#NewWithCredentials) method):

https://github.com/hellofresh/kangal/blob/37a89a3569a310c2a501478fd8b0c055ad436293/pkg/report/report.go#L59

Being able to enable encryption in transit would be a good option to have from a [security perspective](https://docs.aws.amazon.com/AmazonS3/latest/userguide/security-best-practices.html#transit).

Perhaps this could be implemented in a backwards compatible manner, so the default is `secure` set to `false` but this could be set to `true` using configuration?

**Comment by diegomarangoni** [comment]
hey @jleft, thanks for reporting!

I opened a PR to fix issue #127

**Comment by jleft** [comment]
Brilliant, thanks @diegomarangoni!
