### ISSUE TITLE
Custom locust images for master and worker

### ISSUE THREAD

**Issue by jdani** [hellofresh/kangal#146]
The helm chart documentation says this for the locust image:

**configmap.LOCUST_IMAGE_NAME: Default Locust image name/repository if none is provided when creating a new loadtest**

I understand it like there is a way to specify in each new loadtest the image to use for locust.
To get so I tried with the envvars file defining the following:
```
"LOCUST_IMAGE_NAME","thisisnotaninamge/locust"
"LOCUST_IMAGE","thisisnotaninamge/locust"
"LOCUST_IMAGE_TAG","noimage"
```

But even in that case the default image is used.

Is this a bug? Is this the right mechanism to use a custom locust image in a per loadtest basis?

**Comment by s4nji** [comment]
Hey @jdani 👋 

The environment variables you mentioned are meant to be set on the controller, which can be done in the helm chart `values.yaml` file (either in the [configmap](https://github.com/hellofresh/kangal/blob/8bff1fa11545d020429e8d56e724a4dae0cb7643/charts/kangal/values.yaml#L179-L180) or [controller environment variables](https://github.com/hellofresh/kangal/blob/8bff1fa11545d020429e8d56e724a4dae0cb7643/charts/kangal/values.yaml#L127-L128)).

**Comment by jdani** [comment]
Ok, I get it. But I'm looking for a way to define the image to use in a per loadtest basis. Is that possible? I don't think so. But would it be interesting? I can try to code it, at least for Locust backend. My idea is to use the env vars to read LOCUST_IMAGE and LOCUST_TAG and use it in the spec transformers as it is done for resource limits. Would it be something interesting?

**Comment by s-radyuk** [comment]
Hey @jdani !
Thank you for offering your contribution! We appreciate your passion.
Please consider the following option to implement: provide the image from HTTP request. Proxy already has method `fromHTTPRequestToLoadTestSpec` constructing the LoadTestSpec from request. But currently, we don't update MasterConfig and WorkerConfig there. They stay empty and the default image is used.

**Comment by jdani** [comment]
Yep! It seems like a better idea. I will give it a try and will send PR in the coming days

**Comment by jdani** [comment]
Done here: https://github.com/hellofresh/kangal/pull/147

**Comment by jdani** [comment]
@s-radyuk I'm trying to install the latest version via helm, but the docker images are not updated and I neither can find the dockerfile to build them by myself. How can I build the docker images?  Thanks
