### ISSUE TITLE
Persistence options

### ISSUE THREAD

**Issue by alexander-bruun** [hellofresh/kangal#151]
Is there other options rather than AWS S3 persistence? 

Personally I would like to use my own StorageClass that is already setup for persisting data across the cluster, maybe the helm chart / image could be updated to support both approaches instead of being stuck with AWS.

**Comment by lucasmdrs** [comment]
Hi @mr-bruun thank you for your question!

Unfortunately the report storage is only supported by S3 compatible backends. Contributions to support different storage backends are welcome!

Meanwhile, we use [MinIO](https://min.io/) client for S3 communication, if possible you could setup MinIO with your StorageClass for persistence to leverage the supported persistence option

**Comment by mr-bruun** [comment]
Hello @lucasmdrs 

Thanks for the quick reply, could you possibly send me in the right direction within the source code? I have not yet looked into the source code itself, only used it at a top level. 

Then I will take a look at implementing persistence by using kubernetes StorageClass (pv / pvc) resource.

**Comment by lucasmdrs** [comment]
Sure, please take a look at the documentation also to understand the full process of the load test with Kangal.

In the docs section about [Reporting](https://github.com/hellofresh/kangal/tree/master/docs#reporting) you'll see that the backend reports the test results to the Kangal Proxy, using a URL [provided by the Controller](https://github.com/hellofresh/kangal/blob/master/pkg/controller/loadtest.go#L311) during the creation of the load test.


The persistence part of the process is handled in the [report package](https://github.com/hellofresh/kangal/tree/master/pkg/report) which it's initialized in the [Proxy command creation](https://github.com/hellofresh/kangal/blob/master/cmd/proxy.go#L68)

**Comment by alexander-bruun** [comment]
We ended up going with MinIO solution as you suggested, a few things still need to be tweaked to get everything just right.

Integration chain: longhorn -> minio -> kangal -> influxdb -> grafana
