### ISSUE TITLE
Default helm chart value will result queries in swagger to return 404

### ISSUE THREAD

**Issue by alexander-bruun** [hellofresh/kangal#152]
I found issues with the default helm value on the following line: https://github.com/hellofresh/kangal/blob/master/charts/kangal/values.yaml#L79 would cause a 404 error since it will try to append the `/openapi` endpoint in front of the get request endpoint.

Removing `/openapi` from the default helm chart variable on L79 fixed the issue since it no longer makes request to api endpoints with the /openapi in front of the endpoint.

Is this expected behavior?

**Comment by lucasmdrs** [comment]
Hi @mr-bruun

You're correct, the default value is only a placeholder but it's referring to the OpenAPI Spec endpoint, which can be misleading  for new users. Thank you for pointing that out!

Feel free to contribute with this fix if you're interested. Otherwise I'll make the change along the week.

**Comment by mr-bruun** [comment]
@lucasmdrs Pull request with minor change has been created: https://github.com/hellofresh/kangal/pull/153

**Comment by lucasmdrs** [comment]
Solved by #153
