### ISSUE TITLE
Prometheus exporter - Running tests

### ISSUE THREAD

**Issue by amandahla** [hellofresh/kangal#204]
Is there a way to get the number of running tests as Prometheus metrics? A Prometheus exporter for kangal-controller?

We can check that on /load-test but we would like to monitor how many tests are running using Prometheus/Grafana.

**Comment by lucasmdrs** [comment]
Hi Amanda :wave: 

Thank you for your question and interest in Kangal :heart: 

We do provide [some metrics from the controller](https://github.com/hellofresh/kangal/blob/69fee49b200e6fdab5f440335631a96f47bad632/pkg/core/observability/controller.go#L19-L22), they are simple but might be just enough to get the information that you're looking for.

But feel free to provide more details or suggestions if they do not suffice your use case :slightly_smiling_face:

**Comment by amandahla** [comment]
Hi @lucasmdrs :raised_hand_with_fingers_splayed:

Actually we are thinking about something to warn if there are too many tests running and also failed.

Those metrics that you pointed out it's a good start :wink: thanks
