### ISSUE TITLE
CLEANUP_THRESHOLD usage

### ISSUE THREAD

**Issue by amandahla** [hellofresh/kangal#208]
I'm not sure about what would be a expected correct behavior from env var CLEANUP_THRESHOLD.

From the docs: "Life time of a load test"

But it only applies for tests that are Finished or Errored.

Would be useful to have separated vars to control life time of each state (finished, errored and running)?

**Comment by lucasmdrs** [comment]
Hi @amandahla 

The `CLEANUP_THRESHOLD` is used to remove resources that are already completed and no longer needed.

It could be useful to have different thresholds for `Finished` and `Errored` to have more control over the results, but Load Tests that are Running should not be cleaned up.
