### ISSUE TITLE
Fix kubernetes code gen 

### ISSUE THREAD

**Issue by lucasmdrs** [hellofresh/kangal#214]
Currently the code generator script is failing, preventing new contributions to make changes in the CRD.

**Comment by amandahla** [comment]
Maybe update-codegen.sh shouldn't do "rm -rf "$TEMP"" at the end?

**Comment by lucasmdrs** [comment]
Hi @amandahla :wave: 

Thank you for taking the time to check this, that would allow the verification script to work again :+1: 

But I think we'll need to go a bit deeper and improve this process. We don't have much documentation about it and we could automate a few things, for example, the full procedure is:

 - Vendor dependencies `go mod vendor`
 - Grant executable permission to code-generator `chmod +x vendor/k8s.io/code-generator/*.sh`
 - Run the update/verification `./hack/update-codegen.sh`and `./hack/verify-codegen.sh`
 
Probably reducing a few steps and adding this to the Makefile could be a better approach. :robot: 

Also we need to add a note about backward compatibility in the docs, changes to generated-code would likely represent changes to CRDs and a brake all previous installations :memo:

**Comment by amandahla** [comment]
Totally agree @lucasmdrs 
Can I help with this issue?
- [ ] Update docs
- [ ] Automate procedure using Makefile

**Comment by lucasmdrs** [comment]
Yes! Any contribution on this topic is much appreciated :pray:

**Comment by lucasmdrs** [comment]
@amandahla I'll be working on this next week
I'll review your changes and add some checks to our workflows for this too.

Hopefully that will unblock some of the PRs we have that change the CRD like  #225 and #209
