### ISSUE TITLE
How to use "duration" parameter in JMeter?

### ISSUE THREAD

**Issue by ricardasomni** [hellofresh/kangal#217]
"duration" variable can be passed when creating JMeter test, but how to use it in JMeter to control test duration?

**Comment by lucasmdrs** [comment]
Hi @ricardasomni 

Thank you for your question! 

Please check our backends documentation, we have a section on Jmeter backend docs explaining [how to write tests](https://github.com/hellofresh/kangal/tree/master/docs/jmeter#writing-tests) and we cover a bit about the duration on the [ThreadGroup](https://github.com/hellofresh/kangal/blob/master/docs/jmeter/writing-tests.md#thread-group) example.

Writing configuration to the LoadTest backend should also be covered in the provider's [official documentation](https://jmeter.apache.org/usermanual/index.html)

**Comment by ricardasomni** [comment]
My scenario: I want to start load test from Github pipeline where user can enter scenario name, number of thread and duration for the test. Github then does curl to Kangal proxy with those params.

**Comment by ricardasomni** [comment]
Got it, thanks.
