### ISSUE TITLE
Can't query info about load tests that are persisted to backend but no longer in "Finished" state

### ISSUE THREAD

**Issue by jasonbgilroy** [hellofresh/kangal#227]
A short time after a load test goes from Running to Finished state, it is "cleaned up" and no longer shows as Finished.  The report associated with this will have been persisted, but as far as the API is concerned, there is no way to query a test that has been finished but cleaned up.  If we know the name, we can fetch the test report, but if we do not know the name I am unaware of any way (via API) to know anything about the test.

Perhaps this could be accomplished with a "Persisted" state that could be queried, in combination with tags or a time range.

**Comment by lucasmdrs** [comment]
Hi there,

Our current approach to Load Tests are that they are ephemeral, similar to other common Kubernetes resources and once they are finished they can be removed.

We do have some thoughts about how Load Tests are analysed, were historical information can be relevant for comparisons and other use cases, however we don't have any change planed on this yet.

Would it be helpful to have the possibility to disable the removal of completed/error-ed tests entirely?

**Comment by jasonbgilroy** [comment]
Thanks for your response.  I am primarily interested in analyzing and comparing load tests over time, but if this is not something planned in Kangal it may be useful to have the ability to disable the (automatic) removal of completed and error-ed tests as an interim measure.

**Comment by lucasmdrs** [comment]
Hi @jasonbgilroy 
The latest release of Kangal now should support disabling the cleanup behavior by setting the environment variable value to 0.

Please check the docs or the PR linked in this issue for more details.

If we develop anything related to analyzing the test results we'll make sure to have it announced/mentioned on Kangal too.

Thank you for your feedback and patience.
