### ISSUE TITLE
Allow user specified Storage Class for JMeter Custom Data PVC

### ISSUE THREAD

**Issue by jasonbgilroy** [hellofresh/kangal#256]
As far as I can tell, there is no way for the user to specify the storage class for which a JMeter Custom Data PVC will be created.

In my cluster, the default storage class does not support ReadWriteMany, so I am unable to use this feature.  If I had the ability, I could select one of the alternate storage classes which do support ReadWriteMany.

Thanks!

**Comment by jasonbgilroy** [comment]
> Please wait for the reply of the maintaining team, before creating a PR.

I have a fix for this and can submit a PR, if desired.

**Comment by s-radyuk** [comment]
Hello @jasonbgilroy! 
Thank you for bringing this idea and a wish to contribute, we really appreciate it! Our team will be glad to look at your PR 👍
