### ISSUE TITLE
Upload multiple test scripts to k6 via API?

### ISSUE THREAD

**Issue by bogdan-bashev** [hellofresh/kangal#258]
Hello, I have several K6 load tests which depend on external scripts imports for reporting and interacting with the backend like:
- test.js
   - reporting.js
   - auth.js
   - shared.js

Is it possible somehow to upload multiple testFile for execution via API?

I only found some remnants about uploading zip via mysterious` /api/v1/artifacts/upload` but looks like it's no longer exposed by controller/openapi?

**Comment by s-radyuk** [comment]
Hello Bogdan! 
Kangal doesn't allow uploading multiple test files. It's designed to create one loadtest object based one test file. I would suggest to combine all your utility scripts in one file.

**Comment by bogdan-bashev** [comment]
> Hello Bogdan! Kangal doesn't allow uploading multiple test files. It's designed to create one loadtest object based one test file. I would suggest to combine all your utility scripts in one file.

Thanks for confirming this!
