### ISSUE TITLE
JMeter test closed prematurely

### ISSUE THREAD

**Issue by ricardasomni** [hellofresh/kangal#266]
Started JMeter test for 240 minutes, but it was shut down automatically after ~30 minutes. Is there a limit for max test duration?

**Comment by lucasmdrs** [comment]
Hi @ricardasomni 

By default Kangal controller [deletes loadtests that exceed 1h](https://github.com/hellofresh/kangal/blob/ea2b3ce1a31e03bc8d1312f25f13c320d8f02a4f/pkg/controller/loadtest.go#L391-L396) , I'm not sure if that's what happened in your case, but you can try disabling this behavior if you set the `CLEANUP_THRESHOLD=0`

**Comment by ricardasomni** [comment]
will try, thanks
