### ISSUE TITLE
Support google cloud for results uploading

### ISSUE THREAD

**Issue by ricardasomni** [hellofresh/kangal#269]
We use Kangal in our organisation, but organisation does not use AWS, therefore would like to suggest implementing results uploading to Google cloud storage or even a more generic solution to persist test results. 
P.S. we run Kangal from Github actions.

**Comment by lucasmdrs** [comment]
Hi @ricardasomni 

Thank you for raising the issue, there are some possible alternatives before changing the current code.

The report storage implementation is using [MinIO SDK](https://github.com/minio/minio-go) to communicate with the Cloud storage, it is compatible with AWS S3, but should also support other providers.

There's also the possibility of running [MinIO](https://github.com/minio/minio) server as a container. and deploy along with Kangal using [Helmfile](https://github.com/helmfile/helmfile) or as a new Chart having both as dependencies.

Would any of them solve your use case?
