### ISSUE TITLE
Kangal overrides k6 options

### ISSUE THREAD

**Issue by ricardasomni** [hellofresh/kangal#326]
K6 has options which define various test options like execution time, number of VUs (threads) etc. 
In this specific case I want to set number of iterations for the scenario to be equal to the length of test data file. I do something like this in test script:

`options.scenarios["default"].iterations = testData.length;`

This works fine when I run test locally, but if I use Kangal then I can see that Kangal is overriding my provided options with it's own options therefore limiting the ways how I can configure my test. 
Could you confirm this? Any ideas how to fix/workaround it if possible?

Thank you

**Comment by ricardasomni** [comment]
Another quite related question.
In Kangal [docs](https://github.com/hellofresh/kangal/blob/master/docs/k6/README.md) there is this text: 

> "Note: You can specify test configurations through the [options object](https://k6.io/docs/getting-started/running-k6/#using-options) in the javascript code or by using [environment variables](https://k6.io/docs/using-k6/options/)."

My question is - how to specify environment variables for Kangal in this case? Kangal is invoked via HTTP request, not quite clear how I can pass environment variables to be set in those PODs which Kangal will create for test execution.

**Comment by flah00** [comment]
if you have it running already, the open-api ui for kangal is very helpful, you can see endpoint documentation.

try creating a csv of env vars, eg
```
KEY,VALUE
```

you can include this as part of your submission to the kangal proxy, eg

```
curl kangal-proxy.kangal.svc/load-test --fail --connect-timeout 10 -H 'Content-Type: multipart/form-data' -F distributedPods=1 -F testFile=@foo.jmx -F envVars=@env.csv -F type=JMeter -F overwrite=true
```

**Comment by ricardasomni** [comment]
Thanks, I have missed that part in documentation. Will check out.

**Comment by ricardasomni** [comment]
Actually after deeper investigation i found out that Kangal with K6 does not support "scenarios" property in K6 options. Any plans to extend this functionality?

**Comment by flah00** [comment]
@ricardasomni did you find a work around for this limitation?

**Comment by ricardasomni** [comment]
kind of. I am not using "options.scenarios["default"].iterations" anymore since Kangal does not support it. Issue can be closed, but it's something to look at if Kangal - K6 integration will be developed further.
